// levels.js - Default Levels Database for "Enzo Is You" (Categorized)
// Directions: 0 = UP, 1 = RIGHT, 2 = DOWN, 3 = LEFT

const DEFAULT_LEVELS = [
  {
    id: 1,
    category: "intro",
    name: "Enzo Is You",
    width: 15,
    height: 11,
    hint: "Push the rock out of the way and touch the flag. Remember: ENZO IS YOU, FLAG IS WIN, WALL IS STOP, ROCK IS PUSH.",
    entities: [
      ...createBorderWalls(15, 11),
      { id: "w_div1", type: "object", name: "wall", x: 7, y: 1 },
      { id: "w_div2", type: "object", name: "wall", x: 7, y: 2 },
      { id: "w_div3", type: "object", name: "wall", x: 7, y: 3 },
      { id: "w_div4", type: "object", name: "wall", x: 7, y: 4 },
      { id: "w_div6", type: "object", name: "wall", x: 7, y: 6 },
      { id: "w_div7", type: "object", name: "wall", x: 7, y: 7 },
      { id: "w_div8", type: "object", name: "wall", x: 7, y: 8 },
      { id: "w_div9", type: "object", name: "wall", x: 7, y: 9 },
      { id: "r_1", type: "object", name: "rock", x: 7, y: 5 },
      { id: "enzo_player", type: "object", name: "enzo", x: 3, y: 5 },
      { id: "flag_win", type: "object", name: "flag", x: 11, y: 5 },
      { id: "txt_enzo1", type: "word", name: "text", x: 2, y: 2, value: "ENZO" },
      { id: "txt_is1", type: "word", name: "text", x: 3, y: 2, value: "IS" },
      { id: "txt_y1", type: "word", name: "text", x: 4, y: 2, value: "YOU" },
      { id: "txt_w1", type: "word", name: "text", x: 2, y: 8, value: "WALL" },
      { id: "txt_is2", type: "word", name: "text", x: 3, y: 8, value: "IS" },
      { id: "txt_s1", type: "word", name: "text", x: 4, y: 8, value: "STOP" },
      { id: "txt_r1", type: "word", name: "text", x: 10, y: 2, value: "ROCK" },
      { id: "txt_is3", type: "word", name: "text", x: 11, y: 2, value: "IS" },
      { id: "txt_p1", type: "word", name: "text", x: 12, y: 2, value: "PUSH" },
      { id: "txt_f1", type: "word", name: "text", x: 10, y: 8, value: "FLAG" },
      { id: "txt_is4", type: "word", name: "text", x: 11, y: 8, value: "IS" },
      { id: "txt_win1", type: "word", name: "text", x: 12, y: 8, value: "WIN" }
    ]
  },
  {
    id: 2,
    category: "intro",
    name: "Where Do I Go?",
    width: 15,
    height: 11,
    hint: "The rule is broken! Push the word PUSH to complete the rule: ROCK IS PUSH, then move past the rock.",
    entities: [
      ...createBorderWalls(15, 11),
      { id: "w_div1", type: "object", name: "wall", x: 7, y: 1 },
      { id: "w_div2", type: "object", name: "wall", x: 7, y: 2 },
      { id: "w_div3", type: "object", name: "wall", x: 7, y: 3 },
      { id: "w_div4", type: "object", name: "wall", x: 7, y: 4 },
      { id: "w_div6", type: "object", name: "wall", x: 7, y: 6 },
      { id: "w_div7", type: "object", name: "wall", x: 7, y: 7 },
      { id: "w_div8", type: "object", name: "wall", x: 7, y: 8 },
      { id: "w_div9", type: "object", name: "wall", x: 7, y: 9 },
      { id: "r_1", type: "object", name: "rock", x: 7, y: 5 },
      { id: "enzo_player", type: "object", name: "enzo", x: 3, y: 5 },
      { id: "flag_win", type: "object", name: "flag", x: 11, y: 5 },
      { id: "txt_enzo1", type: "word", name: "text", x: 2, y: 2, value: "ENZO" },
      { id: "txt_is1", type: "word", name: "text", x: 3, y: 2, value: "IS" },
      { id: "txt_y1", type: "word", name: "text", x: 4, y: 2, value: "YOU" },
      { id: "txt_w1", type: "word", name: "text", x: 2, y: 8, value: "WALL" },
      { id: "txt_is2", type: "word", name: "text", x: 3, y: 8, value: "IS" },
      { id: "txt_s1", type: "word", name: "text", x: 4, y: 8, value: "STOP" },
      { id: "txt_r1", type: "word", name: "text", x: 10, y: 2, value: "ROCK" },
      { id: "txt_is3", type: "word", name: "text", x: 11, y: 2, value: "IS" },
      { id: "txt_p1", type: "word", name: "text", x: 10, y: 3, value: "PUSH" },
      { id: "txt_f1", type: "word", name: "text", x: 10, y: 8, value: "FLAG" },
      { id: "txt_is4", type: "word", name: "text", x: 11, y: 8, value: "IS" },
      { id: "txt_win1", type: "word", name: "text", x: 12, y: 8, value: "WIN" }
    ]
  },
  {
    id: 3,
    category: "intro",
    name: "Now What Is This?",
    width: 15,
    height: 11,
    hint: "You are the WALL! Move your wall blocks to break the FLAG IS STOP rule, form FLAG IS WIN, then walk into the flag.",
    entities: [
      ...createBorderWalls(15, 11),
      { id: "w_div1", type: "object", name: "wall", x: 7, y: 1 },
      { id: "w_div2", type: "object", name: "wall", x: 7, y: 2 },
      { id: "w_div3", type: "object", name: "wall", x: 7, y: 3 },
      { id: "w_div4", type: "object", name: "wall", x: 7, y: 4 },
      { id: "w_div5", type: "object", name: "wall", x: 7, y: 5 },
      { id: "w_div6", type: "object", name: "wall", x: 7, y: 6 },
      { id: "w_div7", type: "object", name: "wall", x: 7, y: 7 },
      { id: "w_div8", type: "object", name: "wall", x: 7, y: 8 },
      { id: "w_div9", type: "object", name: "wall", x: 7, y: 9 },
      { id: "flag_win", type: "object", name: "flag", x: 11, y: 5 },
      { id: "txt_w1", type: "word", name: "text", x: 2, y: 2, value: "WALL" },
      { id: "txt_is2", type: "word", name: "text", x: 3, y: 2, value: "IS" },
      { id: "txt_y1", type: "word", name: "text", x: 4, y: 2, value: "YOU" },
      { id: "txt_f1", type: "word", name: "text", x: 10, y: 2, value: "FLAG" },
      { id: "txt_is4", type: "word", name: "text", x: 11, y: 2, value: "IS" },
      { id: "txt_s1", type: "word", name: "text", x: 12, y: 2, value: "STOP" },
      { id: "txt_win1", type: "word", name: "text", x: 10, y: 4, value: "WIN" }
    ]
  },
  {
    id: 4,
    category: "intro",
    name: "Out Of Reach",
    width: 15,
    height: 11,
    hint: "Water sinks anything pushed into it. Push rocks into the water channel to form a bridge, then cross to the flag.",
    entities: [
      ...createBorderWalls(15, 11),
      { id: "wat_1", type: "object", name: "water", x: 7, y: 1 },
      { id: "wat_2", type: "object", name: "water", x: 7, y: 2 },
      { id: "wat_3", type: "object", name: "water", x: 7, y: 3 },
      { id: "wat_4", type: "object", name: "water", x: 7, y: 4 },
      { id: "wat_5", type: "object", name: "water", x: 7, y: 5 },
      { id: "wat_6", type: "object", name: "water", x: 7, y: 6 },
      { id: "wat_7", type: "object", name: "water", x: 7, y: 7 },
      { id: "wat_8", type: "object", name: "water", x: 7, y: 8 },
      { id: "wat_9", type: "object", name: "water", x: 7, y: 9 },
      { id: "r_1", type: "object", name: "rock", x: 5, y: 4 },
      { id: "r_2", type: "object", name: "rock", x: 5, y: 5 },
      { id: "r_3", type: "object", name: "rock", x: 5, y: 6 },
      { id: "enzo_player", type: "object", name: "enzo", x: 2, y: 5 },
      { id: "flag_win", type: "object", name: "flag", x: 12, y: 5 },
      { id: "txt_enzo1", type: "word", name: "text", x: 2, y: 2, value: "ENZO" },
      { id: "txt_is1", type: "word", name: "text", x: 3, y: 2, value: "IS" },
      { id: "txt_y1", type: "word", name: "text", x: 4, y: 2, value: "YOU" },
      { id: "txt_r1", type: "word", name: "text", x: 10, y: 2, value: "ROCK" },
      { id: "txt_is3", type: "word", name: "text", x: 11, y: 2, value: "IS" },
      { id: "txt_p1", type: "word", name: "text", x: 12, y: 2, value: "PUSH" },
      { id: "txt_wat1", type: "word", name: "text", x: 2, y: 8, value: "WATER" },
      { id: "txt_is2", type: "word", name: "text", x: 3, y: 8, value: "IS" },
      { id: "txt_sink1", type: "word", name: "text", x: 4, y: 8, value: "SINK" },
      { id: "txt_f1", type: "word", name: "text", x: 10, y: 8, value: "FLAG" },
      { id: "txt_is4", type: "word", name: "text", x: 11, y: 8, value: "IS" },
      { id: "txt_win1", type: "word", name: "text", x: 12, y: 8, value: "WIN" }
    ]
  },
  {
    id: 5,
    category: "intro",
    name: "Still Out Of Reach",
    width: 15,
    height: 11,
    hint: "Skulls block your way, and SKULL IS DEFEAT is active. Push a rock to break the SKULL IS DEFEAT rule alignment.",
    entities: [
      ...createBorderWalls(15, 11),
      { id: "sk_1", type: "object", name: "skull", x: 8, y: 1 },
      { id: "sk_2", type: "object", name: "skull", x: 8, y: 2 },
      { id: "sk_3", type: "object", name: "skull", x: 8, y: 3 },
      { id: "sk_4", type: "object", name: "skull", x: 8, y: 4 },
      { id: "sk_5", type: "object", name: "skull", x: 8, y: 5 },
      { id: "sk_6", type: "object", name: "skull", x: 8, y: 6 },
      { id: "sk_7", type: "object", name: "skull", x: 8, y: 7 },
      { id: "sk_8", type: "object", name: "skull", x: 8, y: 8 },
      { id: "sk_9", type: "object", name: "skull", x: 8, y: 9 },
      { id: "r_1", type: "object", name: "rock", x: 5, y: 4 },
      { id: "r_2", type: "object", name: "rock", x: 5, y: 6 },
      { id: "enzo_player", type: "object", name: "enzo", x: 2, y: 5 },
      { id: "flag_win", type: "object", name: "flag", x: 12, y: 5 },
      { id: "txt_enzo1", type: "word", name: "text", x: 2, y: 2, value: "ENZO" },
      { id: "txt_is1", type: "word", name: "text", x: 3, y: 2, value: "IS" },
      { id: "txt_y1", type: "word", name: "text", x: 4, y: 2, value: "YOU" },
      { id: "txt_r1", type: "word", name: "text", x: 10, y: 2, value: "ROCK" },
      { id: "txt_is3", type: "word", name: "text", x: 11, y: 2, value: "IS" },
      { id: "txt_p1", type: "word", name: "text", x: 12, y: 2, value: "PUSH" },
      { id: "txt_sk_n", type: "word", name: "text", x: 9, y: 7, value: "SKULL" },
      { id: "txt_sk_i", type: "word", name: "text", x: 9, y: 8, value: "IS" },
      { id: "txt_sk_d", type: "word", name: "text", x: 9, y: 9, value: "DEFEAT" },
      { id: "txt_f1", type: "word", name: "text", x: 10, y: 5, value: "FLAG" },
      { id: "txt_is4", type: "word", name: "text", x: 11, y: 5, value: "IS" },
      { id: "txt_win1", type: "word", name: "text", x: 12, y: 5, value: "WIN" }
    ]
  },
  {
    id: 6,
    category: "intro",
    name: "Volcano",
    width: 15,
    height: 11,
    hint: "You are blocked by walls. But you don't need to reach the flag! Try making ROCK IS WIN, then touch the rock.",
    entities: [
      ...createBorderWalls(15, 11),
      { id: "w_div1", type: "object", name: "wall", x: 7, y: 1 },
      { id: "w_div2", type: "object", name: "wall", x: 7, y: 2 },
      { id: "w_div3", type: "object", name: "wall", x: 7, y: 3 },
      { id: "w_div4", type: "object", name: "wall", x: 7, y: 4 },
      { id: "w_div5", type: "object", name: "wall", x: 7, y: 5 },
      { id: "w_div6", type: "object", name: "wall", x: 7, y: 6 },
      { id: "w_div7", type: "object", name: "wall", x: 7, y: 7 },
      { id: "w_div8", type: "object", name: "wall", x: 7, y: 8 },
      { id: "w_div9", type: "object", name: "wall", x: 7, y: 9 },
      { id: "r_1", type: "object", name: "rock", x: 5, y: 5 },
      { id: "enzo_player", type: "object", name: "enzo", x: 2, y: 5 },
      { id: "flag_win", type: "object", name: "flag", x: 12, y: 5 },
      { id: "txt_enzo1", type: "word", name: "text", x: 2, y: 2, value: "ENZO" },
      { id: "txt_is1", type: "word", name: "text", x: 3, y: 2, value: "IS" },
      { id: "txt_y1", type: "word", name: "text", x: 4, y: 2, value: "YOU" },
      { id: "txt_w1", type: "word", name: "text", x: 2, y: 8, value: "WALL" },
      { id: "txt_is2", type: "word", name: "text", x: 3, y: 8, value: "IS" },
      { id: "txt_s1", type: "word", name: "text", x: 4, y: 8, value: "STOP" },
      { id: "txt_r1", type: "word", name: "text", x: 4, y: 4, value: "ROCK" },
      { id: "txt_is3", type: "word", name: "text", x: 4, y: 6, value: "IS" },
      { id: "txt_win1", type: "word", name: "text", x: 3, y: 7, value: "WIN" }
    ]
  },
  {
    id: 7,
    category: "intro",
    name: "Off Limits",
    width: 15,
    height: 11,
    hint: "Wall is currently STOP. Push the word PUSH into WALL IS STOP to make the walls pushable, then move through them.",
    entities: [
      ...createBorderWalls(15, 11),
      { id: "w_div1", type: "object", name: "wall", x: 8, y: 1 },
      { id: "w_div2", type: "object", name: "wall", x: 8, y: 2 },
      { id: "w_div3", type: "object", name: "wall", x: 8, y: 3 },
      { id: "w_div4", type: "object", name: "wall", x: 8, y: 4 },
      { id: "w_div5", type: "object", name: "wall", x: 8, y: 5 },
      { id: "w_div6", type: "object", name: "wall", x: 8, y: 6 },
      { id: "w_div7", type: "object", name: "wall", x: 8, y: 7 },
      { id: "w_div8", type: "object", name: "wall", x: 8, y: 8 },
      { id: "w_div9", type: "object", name: "wall", x: 8, y: 9 },
      { id: "enzo_player", type: "object", name: "enzo", x: 2, y: 5 },
      { id: "flag_win", type: "object", name: "flag", x: 12, y: 5 },
      { id: "txt_enzo1", type: "word", name: "text", x: 2, y: 2, value: "ENZO" },
      { id: "txt_is1", type: "word", name: "text", x: 3, y: 2, value: "IS" },
      { id: "txt_y1", type: "word", name: "text", x: 4, y: 2, value: "YOU" },
      { id: "txt_w1", type: "word", name: "text", x: 2, y: 8, value: "WALL" },
      { id: "txt_is2", type: "word", name: "text", x: 3, y: 8, value: "IS" },
      { id: "txt_s1", type: "word", name: "text", x: 4, y: 8, value: "STOP" },
      { id: "txt_p1", type: "word", name: "text", x: 3, y: 5, value: "PUSH" },
      { id: "txt_f1", type: "word", name: "text", x: 11, y: 2, value: "FLAG" },
      { id: "txt_is4", type: "word", name: "text", x: 12, y: 2, value: "IS" },
      { id: "txt_win1", type: "word", name: "text", x: 13, y: 2, value: "WIN" }
    ]
  },
  {
    id: 8,
    category: "intro",
    name: "Grass Yard",
    width: 15,
    height: 11,
    hint: "Make a plus (+) intersection. Line up FLAG IS WIN vertically, sharing the IS from ENZO IS YOU horizontally.",
    entities: [
      ...createBorderWalls(15, 11),
      { id: "gr_1", type: "object", name: "grass", x: 8, y: 1 },
      { id: "gr_2", type: "object", name: "grass", x: 8, y: 2 },
      { id: "gr_3", type: "object", name: "grass", x: 8, y: 3 },
      { id: "gr_4", type: "object", name: "grass", x: 8, y: 4 },
      { id: "gr_5", type: "object", name: "grass", x: 8, y: 5 },
      { id: "gr_6", type: "object", name: "grass", x: 8, y: 6 },
      { id: "gr_7", type: "object", name: "grass", x: 8, y: 7 },
      { id: "gr_8", type: "object", name: "grass", x: 8, y: 8 },
      { id: "gr_9", type: "object", name: "grass", x: 8, y: 9 },
      { id: "enzo_player", type: "object", name: "enzo", x: 2, y: 5 },
      { id: "flag_win", type: "object", name: "flag", x: 12, y: 5 },
      { id: "txt_enzo1", type: "word", name: "text", x: 2, y: 2, value: "ENZO" },
      { id: "txt_is1", type: "word", name: "text", x: 3, y: 2, value: "IS" },
      { id: "txt_y1", type: "word", name: "text", x: 4, y: 2, value: "YOU" },
      { id: "txt_gr1", type: "word", name: "text", x: 2, y: 8, value: "GRASS" },
      { id: "txt_is2", type: "word", name: "text", x: 3, y: 8, value: "IS" },
      { id: "txt_s1", type: "word", name: "text", x: 4, y: 8, value: "STOP" },
      { id: "txt_f1", type: "word", name: "text", x: 4, y: 4, value: "FLAG" },
      { id: "txt_win1", type: "word", name: "text", x: 4, y: 6, value: "WIN" }
    ]
  },
  {
    id: 9,
    category: "lake",
    name: "Lock",
    width: 15,
    height: 11,
    hint: "A door blocks the way. The key is OPEN and the door is SHUT. Push the key into the door to destroy both, clearing the path.",
    entities: [
      ...createBorderWalls(15, 11),
      { id: "w_div1", type: "object", name: "wall", x: 8, y: 1 },
      { id: "w_div2", type: "object", name: "wall", x: 8, y: 2 },
      { id: "w_div3", type: "object", name: "wall", x: 8, y: 3 },
      { id: "w_div4", type: "object", name: "wall", x: 8, y: 4 },
      { id: "door_1", type: "object", name: "door", x: 8, y: 5 },
      { id: "w_div6", type: "object", name: "wall", x: 8, y: 6 },
      { id: "w_div7", type: "object", name: "wall", x: 8, y: 7 },
      { id: "w_div8", type: "object", name: "wall", x: 8, y: 8 },
      { id: "w_div9", type: "object", name: "wall", x: 8, y: 9 },
      { id: "key_1", type: "object", name: "key", x: 5, y: 5 },
      { id: "enzo_player", type: "object", name: "enzo", x: 2, y: 5 },
      { id: "flag_win", type: "object", name: "flag", x: 12, y: 5 },
      { id: "txt_enzo1", type: "word", name: "text", x: 2, y: 2, value: "ENZO" },
      { id: "txt_is1", type: "word", name: "text", x: 3, y: 2, value: "IS" },
      { id: "txt_y1", type: "word", name: "text", x: 4, y: 2, value: "YOU" },
      { id: "txt_w1", type: "word", name: "text", x: 2, y: 8, value: "WALL" },
      { id: "txt_is2", type: "word", name: "text", x: 3, y: 8, value: "IS" },
      { id: "txt_s1", type: "word", name: "text", x: 4, y: 8, value: "STOP" },
      { id: "txt_k1", type: "word", name: "text", x: 5, y: 2, value: "KEY" },
      { id: "txt_is3", type: "word", name: "text", x: 6, y: 2, value: "IS" },
      { id: "txt_p1", type: "word", name: "text", x: 7, y: 2, value: "PUSH" },
      { id: "txt_d1", type: "word", name: "text", x: 5, y: 8, value: "DOOR" },
      { id: "txt_is5", type: "word", name: "text", x: 6, y: 8, value: "IS" },
      { id: "txt_s2", type: "word", name: "text", x: 7, y: 8, value: "STOP" },
      { id: "txt_k2", type: "word", name: "text", x: 10, y: 7, value: "KEY" },
      { id: "txt_is4", type: "word", name: "text", x: 10, y: 8, value: "IS" },
      { id: "txt_op1", type: "word", name: "text", x: 10, y: 9, value: "OPEN" },
      { id: "txt_d2", type: "word", name: "text", x: 12, y: 7, value: "DOOR" },
      { id: "txt_is6", type: "word", name: "text", x: 12, y: 8, value: "IS" },
      { id: "txt_sh1", type: "word", name: "text", x: 12, y: 9, value: "SHUT" },
      { id: "txt_f1", type: "word", name: "text", x: 11, y: 2, value: "FLAG" },
      { id: "txt_is7", type: "word", name: "text", x: 12, y: 2, value: "IS" },
      { id: "txt_win1", type: "word", name: "text", x: 13, y: 2, value: "WIN" }
    ]
  },
  {
    id: 10,
    category: "lake",
    name: "Novice Locksmith",
    width: 15,
    height: 11,
    hint: "Use the key to unlock the door. Grab the WIN block on the other side and form FLAG IS WIN to win.",
    entities: [
      ...createBorderWalls(15, 11),
      { id: "w_div1", type: "object", name: "wall", x: 8, y: 1 },
      { id: "w_div2", type: "object", name: "wall", x: 8, y: 2 },
      { id: "w_div3", type: "object", name: "wall", x: 8, y: 3 },
      { id: "w_div4", type: "object", name: "wall", x: 8, y: 4 },
      { id: "door_1", type: "object", name: "door", x: 8, y: 5 },
      { id: "w_div6", type: "object", name: "wall", x: 8, y: 6 },
      { id: "w_div7", type: "object", name: "wall", x: 8, y: 7 },
      { id: "w_div8", type: "object", name: "wall", x: 8, y: 8 },
      { id: "w_div9", type: "object", name: "wall", x: 8, y: 9 },
      { id: "key_1", type: "object", name: "key", x: 4, y: 5 },
      { id: "enzo_player", type: "object", name: "enzo", x: 2, y: 5 },
      { id: "flag_win", type: "object", name: "flag", x: 12, y: 5 },
      { id: "txt_enzo1", type: "word", name: "text", x: 2, y: 2, value: "ENZO" },
      { id: "txt_is1", type: "word", name: "text", x: 3, y: 2, value: "IS" },
      { id: "txt_y1", type: "word", name: "text", x: 4, y: 2, value: "YOU" },
      { id: "txt_k1", type: "word", name: "text", x: 2, y: 8, value: "KEY" },
      { id: "txt_is2", type: "word", name: "text", x: 3, y: 8, value: "IS" },
      { id: "txt_p1", type: "word", name: "text", x: 4, y: 8, value: "PUSH" },
      { id: "txt_d1", type: "word", name: "text", x: 5, y: 8, value: "DOOR" },
      { id: "txt_is3", type: "word", name: "text", x: 6, y: 8, value: "IS" },
      { id: "txt_s2", type: "word", name: "text", x: 7, y: 8, value: "STOP" },
      { id: "txt_k2", type: "word", name: "text", x: 11, y: 7, value: "KEY" },
      { id: "txt_is4", type: "word", name: "text", x: 11, y: 8, value: "IS" },
      { id: "txt_op1", type: "word", name: "text", x: 11, y: 9, value: "OPEN" },
      { id: "txt_d2", type: "word", name: "text", x: 13, y: 7, value: "DOOR" },
      { id: "txt_is6", type: "word", name: "text", x: 13, y: 8, value: "IS" },
      { id: "txt_sh1", type: "word", name: "text", x: 13, y: 9, value: "SHUT" },
      { id: "txt_f1", type: "word", name: "text", x: 11, y: 2, value: "FLAG" },
      { id: "txt_is7", type: "word", name: "text", x: 12, y: 2, value: "IS" },
      { id: "txt_win1", type: "word", name: "text", x: 12, y: 3, value: "WIN" }
    ]
  },
  {
    id: 11,
    category: "lake",
    name: "Locked In",
    width: 15,
    height: 11,
    hint: "Enzo is locked inside walls. The key is in another room. Form KEY IS YOU to control the key, escape, unlock Enzo, and win.",
    entities: [
      ...createBorderWalls(15, 11),
      // Left room (Enzo)
      { id: "w_r1", type: "object", name: "wall", x: 4, y: 1 },
      { id: "w_r2", type: "object", name: "wall", x: 4, y: 2 },
      { id: "w_r3", type: "object", name: "wall", x: 4, y: 3 },
      { id: "w_r4", type: "object", name: "wall", x: 4, y: 4 },
      { id: "door_1", type: "object", name: "door", x: 4, y: 5 },
      { id: "w_r6", type: "object", name: "wall", x: 4, y: 6 },
      { id: "w_r7", type: "object", name: "wall", x: 4, y: 7 },
      { id: "w_r8", type: "object", name: "wall", x: 4, y: 8 },
      { id: "w_r9", type: "object", name: "wall", x: 4, y: 9 },
      // Right room (Key)
      { id: "w_r10", type: "object", name: "wall", x: 10, y: 1 },
      { id: "w_r11", type: "object", name: "wall", x: 10, y: 2 },
      { id: "w_r12", type: "object", name: "wall", x: 10, y: 3 },
      { id: "w_r13", type: "object", name: "wall", x: 10, y: 4 },
      { id: "w_r14", type: "object", name: "wall", x: 10, y: 5 },
      { id: "w_r15", type: "object", name: "wall", x: 10, y: 6 },
      { id: "w_r16", type: "object", name: "wall", x: 10, y: 7 },
      { id: "w_r17", type: "object", name: "wall", x: 10, y: 8 },
      { id: "w_r18", type: "object", name: "wall", x: 10, y: 9 },
      { id: "enzo_player", type: "object", name: "enzo", x: 2, y: 5 },
      { id: "key_1", type: "object", name: "key", x: 12, y: 2 },
      { id: "flag_win", type: "object", name: "flag", x: 12, y: 8 },
      { id: "txt_enzo1", type: "word", name: "text", x: 2, y: 2, value: "ENZO" },
      { id: "txt_is1", type: "word", name: "text", x: 3, y: 2, value: "IS" },
      { id: "txt_y1", type: "word", name: "text", x: 2, y: 3, value: "YOU" },
      { id: "txt_w1", type: "word", name: "text", x: 2, y: 8, value: "WALL" },
      { id: "txt_is2", type: "word", name: "text", x: 3, y: 8, value: "IS" },
      { id: "txt_s1", type: "word", name: "text", x: 2, y: 9, value: "STOP" },
      { id: "txt_k1", type: "word", name: "text", x: 7, y: 2, value: "KEY" },
      { id: "txt_is3", type: "word", name: "text", x: 7, y: 3, value: "IS" },
      { id: "txt_p1", type: "word", name: "text", x: 7, y: 4, value: "PUSH" },
      { id: "txt_k2", type: "word", name: "text", x: 7, y: 6, value: "KEY" },
      { id: "txt_is4", type: "word", name: "text", x: 7, y: 7, value: "IS" },
      { id: "txt_op1", type: "word", name: "text", x: 7, y: 8, value: "OPEN" },
      { id: "txt_d1", type: "word", name: "text", x: 11, y: 4, value: "DOOR" },
      { id: "txt_is5", type: "word", name: "text", x: 12, y: 4, value: "IS" },
      { id: "txt_s2", type: "word", name: "text", x: 13, y: 4, value: "SHUT" },
      { id: "txt_f1", type: "word", name: "text", x: 11, y: 6, value: "FLAG" },
      { id: "txt_is6", type: "word", name: "text", x: 12, y: 6, value: "IS" },
      { id: "txt_win1", type: "word", name: "text", x: 13, y: 6, value: "WIN" }
    ]
  },
  {
    id: 12,
    category: "lake",
    name: "Love Throne",
    width: 15,
    height: 11,
    hint: "Love hearts block the way, but they can be pushed. SINK the lava stream by pushing hearts into it.",
    entities: [
      ...createBorderWalls(15, 11),
      { id: "lav_1", type: "object", name: "lava", x: 7, y: 1 },
      { id: "lav_2", type: "object", name: "lava", x: 7, y: 2 },
      { id: "lav_3", type: "object", name: "lava", x: 7, y: 3 },
      { id: "lav_4", type: "object", name: "lava", x: 7, y: 4 },
      { id: "lav_5", type: "object", name: "lava", x: 7, y: 5 },
      { id: "lav_6", type: "object", name: "lava", x: 7, y: 6 },
      { id: "lav_7", type: "object", name: "lava", x: 7, y: 7 },
      { id: "lav_8", type: "object", name: "lava", x: 7, y: 8 },
      { id: "lav_9", type: "object", name: "lava", x: 7, y: 9 },
      { id: "love_1", type: "object", name: "love", x: 4, y: 4 },
      { id: "love_2", type: "object", name: "love", x: 4, y: 5 },
      { id: "love_3", type: "object", name: "love", x: 4, y: 6 },
      { id: "enzo_player", type: "object", name: "enzo", x: 2, y: 5 },
      { id: "flag_win", type: "object", name: "flag", x: 12, y: 5 },
      { id: "txt_enzo1", type: "word", name: "text", x: 2, y: 2, value: "ENZO" },
      { id: "txt_is1", type: "word", name: "text", x: 3, y: 2, value: "IS" },
      { id: "txt_y1", type: "word", name: "text", x: 4, y: 2, value: "YOU" },
      { id: "txt_lv1", type: "word", name: "text", x: 2, y: 8, value: "LOVE" },
      { id: "txt_is2", type: "word", name: "text", x: 3, y: 8, value: "IS" },
      { id: "txt_p1", type: "word", name: "text", x: 4, y: 8, value: "PUSH" },
      { id: "txt_la1", type: "word", name: "text", x: 10, y: 7, value: "LAVA" },
      { id: "txt_is3", type: "word", name: "text", x: 11, y: 7, value: "IS" },
      { id: "txt_sk1", type: "word", name: "text", x: 12, y: 7, value: "SINK" },
      { id: "txt_f1", type: "word", name: "text", x: 10, y: 2, value: "FLAG" },
      { id: "txt_is4", type: "word", name: "text", x: 11, y: 2, value: "IS" },
      { id: "txt_win1", type: "word", name: "text", x: 12, y: 2, value: "WIN" }
    ]
  },
  {
    id: 13,
    category: "lake",
    name: "Change of Heart",
    width: 15,
    height: 11,
    hint: "The flag is trapped inside walls, and there's no path. But what if the walls themselves turned into Enzos? Form: WALL IS ENZO.",
    entities: [
      ...createBorderWalls(15, 11),
      { id: "w_box1", type: "object", name: "wall", x: 10, y: 4 },
      { id: "w_box2", type: "object", name: "wall", x: 10, y: 5 },
      { id: "w_box3", type: "object", name: "wall", x: 10, y: 6 },
      { id: "w_box4", type: "object", name: "wall", x: 11, y: 4 },
      { id: "w_box5", type: "object", name: "wall", x: 12, y: 4 },
      { id: "w_box6", type: "object", name: "wall", x: 12, y: 5 },
      { id: "w_box7", type: "object", name: "wall", x: 12, y: 6 },
      { id: "w_box8", type: "object", name: "wall", x: 11, y: 6 },
      { id: "flag_win", type: "object", name: "flag", x: 11, y: 5 },
      { id: "enzo_player", type: "object", name: "enzo", x: 2, y: 5 },
      { id: "txt_enzo1", type: "word", name: "text", x: 2, y: 2, value: "ENZO" },
      { id: "txt_is1", type: "word", name: "text", x: 3, y: 2, value: "IS" },
      { id: "txt_y1", type: "word", name: "text", x: 4, y: 2, value: "YOU" },
      { id: "txt_w1", type: "word", name: "text", x: 2, y: 8, value: "WALL" },
      { id: "txt_is2", type: "word", name: "text", x: 3, y: 8, value: "IS" },
      { id: "txt_s1", type: "word", name: "text", x: 4, y: 8, value: "STOP" },
      { id: "txt_f1", type: "word", name: "text", x: 10, y: 2, value: "FLAG" },
      { id: "txt_is4", type: "word", name: "text", x: 11, y: 2, value: "IS" },
      { id: "txt_win1", type: "word", name: "text", x: 12, y: 2, value: "WIN" },
      { id: "txt_w2", type: "word", name: "text", x: 5, y: 4, value: "WALL" },
      { id: "txt_is3", type: "word", name: "text", x: 5, y: 5, value: "IS" },
      { id: "txt_enzo2", type: "word", name: "text", x: 5, y: 6, value: "ENZO" }
    ]
  },
  {
    id: 14,
    category: "island",
    name: "Double Mind",
    width: 15,
    height: 11,
    hint: "Control both ENZO and KEKE together! Push the key into the locked gate using Keke, while avoiding the deadly skulls.",
    entities: [
      ...createBorderWalls(15, 11),
      { id: "w_div1", type: "object", name: "wall", x: 7, y: 1 },
      { id: "w_div2", type: "object", name: "wall", x: 7, y: 2 },
      { id: "w_div3", type: "object", name: "wall", x: 7, y: 3 },
      { id: "w_div4", type: "object", name: "wall", x: 7, y: 4 },
      { id: "door_1", type: "object", name: "door", x: 7, y: 5 },
      { id: "w_div6", type: "object", name: "wall", x: 7, y: 6 },
      { id: "w_div7", type: "object", name: "wall", x: 7, y: 7 },
      { id: "w_div8", type: "object", name: "wall", x: 7, y: 8 },
      { id: "w_div9", type: "object", name: "wall", x: 7, y: 9 },
      { id: "key_1", type: "object", name: "key", x: 4, y: 2 },
      { id: "enzo_player", type: "object", name: "enzo", x: 2, y: 3 },
      { id: "keke_player", type: "object", name: "keke", x: 2, y: 7 },
      { id: "sk_1", type: "object", name: "skull", x: 5, y: 5 },
      { id: "sk_2", type: "object", name: "skull", x: 6, y: 5 },
      { id: "flag_win", type: "object", name: "flag", x: 12, y: 5 },
      { id: "txt_enzo1", type: "word", name: "text", x: 2, y: 1, value: "ENZO" },
      { id: "txt_is1", type: "word", name: "text", x: 3, y: 1, value: "IS" },
      { id: "txt_y1", type: "word", name: "text", x: 4, y: 1, value: "YOU" },
      { id: "txt_k1", type: "word", name: "text", x: 2, y: 9, value: "KEKE" },
      { id: "txt_is2", type: "word", name: "text", x: 3, y: 9, value: "IS" },
      { id: "txt_y2", type: "word", name: "text", x: 4, y: 9, value: "YOU" },
      { id: "txt_sk1", type: "word", name: "text", x: 9, y: 7, value: "SKULL" },
      { id: "txt_is3", type: "word", name: "text", x: 9, y: 8, value: "IS" },
      { id: "txt_def1", type: "word", name: "text", x: 9, y: 9, value: "DEFEAT" },
      { id: "txt_w1", type: "word", name: "text", x: 11, y: 1, value: "WALL" },
      { id: "txt_is4", type: "word", name: "text", x: 12, y: 1, value: "IS" },
      { id: "txt_s1", type: "word", name: "text", x: 13, y: 1, value: "STOP" },
      { id: "txt_k_push", type: "word", name: "text", x: 11, y: 2, value: "KEY" },
      { id: "txt_is5", type: "word", name: "text", x: 12, y: 2, value: "IS" },
      { id: "txt_p1", type: "word", name: "text", x: 13, y: 2, value: "PUSH" },
      { id: "txt_d1", type: "word", name: "text", x: 11, y: 7, value: "DOOR" },
      { id: "txt_is6", type: "word", name: "text", x: 11, y: 8, value: "IS" },
      { id: "txt_s2", type: "word", name: "text", x: 11, y: 9, value: "STOP" },
      { id: "txt_sh1", type: "word", name: "text", x: 10, y: 8, value: "SHUT" },
      { id: "txt_k_op", type: "word", name: "text", x: 13, y: 7, value: "KEY" },
      { id: "txt_is7", type: "word", name: "text", x: 13, y: 8, value: "IS" },
      { id: "txt_op1", type: "word", name: "text", x: 13, y: 9, value: "OPEN" },
      { id: "txt_f1", type: "word", name: "text", x: 11, y: 3, value: "FLAG" },
      { id: "txt_is8", type: "word", name: "text", x: 12, y: 3, value: "IS" },
      { id: "txt_win1", type: "word", name: "text", x: 13, y: 3, value: "WIN" }
    ]
  },
  {
    id: 15,
    category: "island",
    name: "Tiny Pond",
    width: 15,
    height: 11,
    hint: "The flag is inside a pond of SINK water. Make KEY IS YOU to control the key, walk it into the water to sink it, and free the flag.",
    entities: [
      ...createBorderWalls(15, 11),
      // The Water Pond (outer ring)
      { id: "wt_p1", type: "object", name: "water", x: 7, y: 3 },
      { id: "wt_p2", type: "object", name: "water", x: 7, y: 4 },
      { id: "wt_p3", type: "object", name: "water", x: 7, y: 5 },
      { id: "wt_p4", type: "object", name: "water", x: 7, y: 6 },
      { id: "wt_p5", type: "object", name: "water", x: 7, y: 7 },
      { id: "wt_p6", type: "object", name: "water", x: 8, y: 3 },
      { id: "wt_p7", type: "object", name: "water", x: 9, y: 3 },
      { id: "wt_p8", type: "object", name: "water", x: 9, y: 4 },
      { id: "wt_p9", type: "object", name: "water", x: 9, y: 5 },
      { id: "wt_p10", type: "object", name: "water", x: 9, y: 6 },
      { id: "wt_p11", type: "object", name: "water", x: 9, y: 7 },
      { id: "wt_p12", type: "object", name: "water", x: 8, y: 7 },
      // Trapped Flag
      { id: "flag_win", type: "object", name: "flag", x: 8, y: 5 },
      
      { id: "enzo_player", type: "object", name: "enzo", x: 2, y: 3 },
      { id: "key_1", type: "object", name: "key", x: 2, y: 7 },
      
      // Initial rules
      { id: "txt_enzo1", type: "word", name: "text", x: 2, y: 1, value: "ENZO" },
      { id: "txt_is1", type: "word", name: "text", x: 3, y: 1, value: "IS" },
      { id: "txt_y1", type: "word", name: "text", x: 4, y: 1, value: "YOU" },
      
      { id: "txt_wt1", type: "word", name: "text", x: 10, y: 9, value: "WATER" },
      { id: "txt_is2", type: "word", name: "text", x: 11, y: 9, value: "IS" },
      { id: "txt_snk", type: "word", name: "text", x: 12, y: 9, value: "SINK" },
      
      { id: "txt_f1", type: "word", name: "text", x: 11, y: 2, value: "FLAG" },
      { id: "txt_is3", type: "word", name: "text", x: 12, y: 2, value: "IS" },
      { id: "txt_wn1", type: "word", name: "text", x: 13, y: 2, value: "WIN" },
      
      // Floating rule blocks to swap
      { id: "txt_k1", type: "word", name: "text", x: 4, y: 4, value: "KEY" },
      { id: "txt_is4", type: "word", name: "text", x: 4, y: 5, value: "IS" },
      { id: "txt_y2", type: "word", name: "text", x: 4, y: 6, value: "YOU" }
    ]
  },
  {
    id: 16,
    category: "island",
    name: "Prison",
    width: 15,
    height: 11,
    hint: "Escape the prison of doors! Push keys into doors to unlock them, rearrange rules, and reach the Flag.",
    entities: [
      ...createBorderWalls(15, 11),
      // Maze of walls and doors
      { id: "w_p1", type: "object", name: "wall", x: 5, y: 1 },
      { id: "w_p2", type: "object", name: "wall", x: 5, y: 2 },
      { id: "w_p3", type: "object", name: "wall", x: 5, y: 3 },
      { id: "door_1", type: "object", name: "door", x: 5, y: 4 },
      { id: "w_p4", type: "object", name: "wall", x: 5, y: 5 },
      { id: "door_2", type: "object", name: "door", x: 5, y: 6 },
      { id: "w_p5", type: "object", name: "wall", x: 5, y: 7 },
      { id: "w_p6", type: "object", name: "wall", x: 5, y: 8 },
      { id: "w_p7", type: "object", name: "wall", x: 5, y: 9 },
      { id: "w_p8", type: "object", name: "wall", x: 10, y: 1 },
      { id: "w_p9", type: "object", name: "wall", x: 10, y: 2 },
      { id: "door_3", type: "object", name: "door", x: 10, y: 3 },
      { id: "w_p10", type: "object", name: "wall", x: 10, y: 4 },
      { id: "w_p11", type: "object", name: "wall", x: 10, y: 5 },
      { id: "door_4", type: "object", name: "door", x: 10, y: 6 },
      { id: "w_p12", type: "object", name: "wall", x: 10, y: 7 },
      { id: "w_p13", type: "object", name: "wall", x: 10, y: 8 },
      { id: "w_p14", type: "object", name: "wall", x: 10, y: 9 },
      { id: "enzo_player", type: "object", name: "enzo", x: 2, y: 5 },
      { id: "key_1", type: "object", name: "key", x: 3, y: 3 },
      { id: "key_2", type: "object", name: "key", x: 3, y: 7 },
      { id: "key_3", type: "object", name: "key", x: 7, y: 5 },
      { id: "flag_win", type: "object", name: "flag", x: 12, y: 5 },
      { id: "txt_enzo1", type: "word", name: "text", x: 2, y: 1, value: "ENZO" },
      { id: "txt_is1", type: "word", name: "text", x: 3, y: 1, value: "IS" },
      { id: "txt_y1", type: "word", name: "text", x: 4, y: 1, value: "YOU" },
      { id: "txt_w1", type: "word", name: "text", x: 2, y: 9, value: "WALL" },
      { id: "txt_is2", type: "word", name: "text", x: 3, y: 9, value: "IS" },
      { id: "txt_s1", type: "word", name: "text", x: 4, y: 9, value: "STOP" },
      { id: "txt_k1", type: "word", name: "text", x: 7, y: 1, value: "KEY" },
      { id: "txt_is3", type: "word", name: "text", x: 7, y: 2, value: "IS" },
      { id: "txt_p1", type: "word", name: "text", x: 7, y: 3, value: "PUSH" },
      { id: "txt_k2", type: "word", name: "text", x: 7, y: 7, value: "KEY" },
      { id: "txt_is4", type: "word", name: "text", x: 7, y: 8, value: "IS" },
      { id: "txt_op1", type: "word", name: "text", x: 7, y: 9, value: "OPEN" },
      { id: "txt_d1", type: "word", name: "text", x: 12, y: 7, value: "DOOR" },
      { id: "txt_is5", type: "word", name: "text", x: 12, y: 8, value: "IS" },
      { id: "txt_sh1", type: "word", name: "text", x: 12, y: 9, value: "SHUT" },
      { id: "txt_d2", type: "word", name: "text", x: 11, y: 1, value: "DOOR" },
      { id: "txt_is6", type: "word", name: "text", x: 12, y: 1, value: "IS" },
      { id: "txt_s2", type: "word", name: "text", x: 13, y: 1, value: "STOP" },
      { id: "txt_f1", type: "word", name: "text", x: 11, y: 3, value: "FLAG" },
      { id: "txt_is7", type: "word", name: "text", x: 12, y: 3, value: "IS" },
      { id: "txt_win1", type: "word", name: "text", x: 13, y: 3, value: "WIN" }
    ]
  }
];

// Helper to create border walls
function createBorderWalls(w, h) {
  const walls = [];
  let idCounter = 0;
  for (let x = 0; x < w; x++) {
    walls.push({ id: `w_b_${idCounter++}`, type: "object", name: "wall", x: x, y: 0, dir: 1 });
    walls.push({ id: `w_b_${idCounter++}`, type: "object", name: "wall", x: x, y: h - 1, dir: 1 });
  }
  for (let y = 1; y < h - 1; y++) {
    walls.push({ id: `w_b_${idCounter++}`, type: "object", name: "wall", x: 0, y: y, dir: 1 });
    walls.push({ id: `w_b_${idCounter++}`, type: "object", name: "wall", x: w - 1, y: y, dir: 1 });
  }
  return walls;
}
